from __future__ import annotations

TOOL_SLUGS: dict[str, str] = {
    "ProGen / ProGen2": "progen",
    "EvoDiff": "evodiff",
    "ESM3": "esm3",
    "ProteinMPNN": "proteinmpnn",
    "ESM-IF1": "esm-if1",
    "LigandMPNN": "ligandmpnn",
    "AntiFold": "antifold",
    "RFdiffusion": "rfdiffusion",
    "RFdiffusion All-Atom (RFdiffusionAA)": "rfdiffusion-aa",
    "Chroma": "chroma",
    "FrameDiff": "framediff",
    "ProteinGenerator": "protein-generator",
    "BindCraft": "bindcraft",
    "AlphaProteo": "alphaproteo",
    "BoltzGen": "boltzgen",
    "RFantibody": "rfantibody",
    "tFold System": "tfold",
    "PALM-H3": "palm-h3",
    "DiffAb": "diffab",
    "dyMEAN": "dymean",
    "IgLM": "iglm",
    "FlowDesign": "flowdesign",
    "AbDiffuser": "abdiffuser",
    "Humatch": "humatch",
    "HuDiff": "hudiff",
    "HuAbDiffusion": "huabdiffusion",
    "Efficient evolution with ESM-1v": "esm-1v-efficient-evolution",
    "Structural evolution (ESM-IF1 complex)": "structural-evolution",
    "EVOLVEpro": "evolvepro",
    "Makowski et al. affinity–specificity co-optimization": "makowski-affinity-specificity",
}

ALIASES: dict[str, list[str]] = {
    "progen": ["ProGen", "ProGen2"],
    "evodiff": ["EvoDiff"],
    "esm3": ["ESM-3", "ESM 3"],
    "proteinmpnn": ["ProteinMPNN", "MPNN"],
    "esm-if1": ["ESM-IF1", "ESM Inverse Folding"],
    "ligandmpnn": ["LigandMPNN"],
    "antifold": ["AntiFold"],
    "rfdiffusion": ["RFdiffusion", "RoseTTAFold diffusion"],
    "rfdiffusion-aa": ["RFdiffusionAA", "RFdiffusion All-Atom"],
    "chroma": ["Chroma"],
    "framediff": ["FrameDiff", "SE(3) diffusion"],
    "protein-generator": ["ProteinGenerator"],
    "bindcraft": ["BindCraft"],
    "alphaproteo": ["AlphaProteo"],
    "boltzgen": ["BoltzGen"],
    "rfantibody": ["RFantibody"],
    "tfold": ["tFold", "tFold-Ab", "tFold-Ag"],
    "palm-h3": ["PALM-H3", "PALM"],
    "diffab": ["DiffAb"],
    "dymean": ["dyMEAN", "dyMEANOpt"],
    "iglm": ["IgLM"],
    "flowdesign": ["FlowDesign"],
    "abdiffuser": ["AbDiffuser"],
    "humatch": ["Humatch"],
    "hudiff": ["HuDiff", "HuDiff-Ab", "HuDiff-Nb"],
    "huabdiffusion": ["HuAbDiffusion", "YabXnization"],
    "esm-1v-efficient-evolution": ["ESM-1v", "efficient evolution"],
    "structural-evolution": ["structural evolution", "ESM-IF1 complex evolution"],
    "evolvepro": ["EVOLVEpro", "EvolvePro"],
    "makowski-affinity-specificity": ["Makowski", "emibetuzumab co-optimization"],
}

PAPER_TITLES: dict[str, str] = {
    "progen": "Large language models generate functional protein sequences across diverse families",
    "evodiff": "Protein generation with evolutionary diffusion: sequence is all you need",
    "esm3": "Simulating 500 million years of evolution with a language model",
    "proteinmpnn": "Robust deep learning-based protein sequence design using ProteinMPNN",
    "esm-if1": "Learning inverse folding from millions of predicted structures",
    "ligandmpnn": "Atomic context-conditioned protein sequence design using LigandMPNN",
    "antifold": "AntiFold: improved structure-based antibody design using inverse folding",
    "rfdiffusion": "De novo design of protein structure and function with RFdiffusion",
    "rfdiffusion-aa": "Generalized biomolecular modeling and design with RoseTTAFold All-Atom",
    "chroma": "Illuminating protein space with a programmable generative model",
    "framediff": "SE(3) diffusion model with application to protein backbone generation",
    "protein-generator": "Generalized biomolecular modeling and design with sequence-space diffusion",
    "bindcraft": "BindCraft: one-shot design of functional protein binders",
    "alphaproteo": "AlphaProteo generates novel proteins for biology and health",
    "boltzgen": "BoltzGen: universal binder design",
    "rfantibody": "Atomically accurate de novo design of antibodies with RFantibody",
    "tfold": "tFold: epitope-specific de novo antibody design",
    "palm-h3": "xTrimoPGLM-based antigen-specific antibody CDR-H3 design (PALM-H3)",
    "diffab": "Antigen-Specific Antibody Design and Optimization with Diffusion-Based Generative Models for Protein Structures",
    "dymean": "End-to-End Full-Atom Antibody Design",
    "iglm": "IgLM: Infilling language modeling for antibody sequence design",
    "flowdesign": "Flow matching for antibody CDR sequence–structure co-design",
    "abdiffuser": "AbDiffuser: full-atom generation of in vitro functioning antibodies",
    "humatch": "Humatch: fast and accurate antibody humanization",
    "hudiff": "Humanization of antibodies and nanobodies by diffusion models",
    "huabdiffusion": "HuAbDiffusion: humanized antibody generation from CDRs",
    "esm-1v-efficient-evolution": "Efficient evolution of human antibodies from general protein language models",
    "structural-evolution": "Unsupervised evolution of protein and antibody complexes with a structure-informed language model",
    "evolvepro": "Few-shot learning for protein evolution with EVOLVEpro",
    "makowski-affinity-specificity": "Co-optimization of therapeutic antibody affinity and specificity using machine learning models of sequence-activity data",
}

# Conservative: only titles that are tightly bound to the listed DOI / venue.
# Several Excel rows mix family names; titles remain review-queue if uncertain.
PAPER_TITLE_CONFIDENCE: dict[str, str] = {
    "protein-generator": "review-queue",
    "tfold": "review-queue",
    "palm-h3": "review-queue",
    "flowdesign": "review-queue",
    "hudiff": "review-queue",
    "huabdiffusion": "review-queue",
    "boltzgen": "review-queue",
    "rfantibody": "review-queue",
    "bindcraft": "review-queue",
    "evolvepro": "review-queue",
    "iglm": "review-queue",
    "abdiffuser": "review-queue",
}

ARCHITECTURE_IDS: dict[str, list[str]] = {
    "progen": ["protein-language-models", "autoregressive-generation"],
    "evodiff": ["sequence-diffusion", "masked-token-infilling"],
    "esm3": ["protein-language-models", "masked-token-infilling", "joint-sequence-structure-generation"],
    "proteinmpnn": ["inverse-folding", "graph-neural-networks"],
    "esm-if1": ["inverse-folding", "geometric-transformers", "se3-equivariant-models"],
    "ligandmpnn": ["inverse-folding", "graph-neural-networks"],
    "antifold": ["inverse-folding", "geometric-transformers"],
    "rfdiffusion": ["frame-diffusion", "coordinate-diffusion", "se3-equivariant-models"],
    "rfdiffusion-aa": ["coordinate-diffusion", "se3-equivariant-models"],
    "chroma": ["coordinate-diffusion", "graph-neural-networks", "joint-sequence-structure-generation"],
    "framediff": ["frame-diffusion", "se3-equivariant-models"],
    "protein-generator": ["sequence-diffusion", "joint-sequence-structure-generation"],
    "bindcraft": ["inverse-folding", "multi-objective-optimization"],
    "alphaproteo": ["joint-sequence-structure-generation"],
    "boltzgen": ["joint-sequence-structure-diffusion", "coordinate-diffusion"],
    "rfantibody": ["frame-diffusion", "inverse-folding", "se3-equivariant-models"],
    "tfold": ["protein-language-models", "geometric-transformers"],
    "palm-h3": ["protein-language-models", "autoregressive-generation"],
    "diffab": ["joint-sequence-structure-diffusion", "se3-equivariant-models", "coordinate-diffusion"],
    "dymean": ["graph-neural-networks", "se3-equivariant-models", "joint-sequence-structure-generation"],
    "iglm": ["protein-language-models", "autoregressive-generation", "masked-token-infilling"],
    "flowdesign": ["flow-matching", "joint-sequence-structure-generation"],
    "abdiffuser": ["joint-sequence-structure-diffusion", "se3-equivariant-models"],
    "humatch": ["multi-objective-optimization"],
    "hudiff": ["sequence-diffusion", "autoregressive-generation"],
    "huabdiffusion": ["sequence-diffusion"],
    "esm-1v-efficient-evolution": ["protein-language-models", "zero-shot-mutation-scoring"],
    "structural-evolution": ["inverse-folding", "zero-shot-mutation-scoring"],
    "evolvepro": ["protein-language-models", "active-learning", "few-shot-mutation-optimization"],
    "makowski-affinity-specificity": ["multi-objective-optimization", "few-shot-mutation-optimization"],
}

TASK_IDS: dict[str, list[str]] = {
    "progen": ["general-protein-sequence-generation"],
    "evodiff": ["general-protein-sequence-generation", "motif-scaffolding"],
    "esm3": ["general-protein-sequence-generation", "joint-sequence-structure-generation", "functional-site-design"],
    "proteinmpnn": ["inverse-folding"],
    "esm-if1": ["inverse-folding", "single-mutation-proposal"],
    "ligandmpnn": ["inverse-folding", "functional-site-design"],
    "antifold": ["inverse-folding", "antibody-structure-aware-sequence-design", "cdr-sequence-generation"],
    "rfdiffusion": ["de-novo-backbone-generation", "motif-scaffolding", "target-conditioned-binder-generation"],
    "rfdiffusion-aa": ["de-novo-backbone-generation", "functional-site-design"],
    "chroma": ["de-novo-backbone-generation", "joint-sequence-structure-generation", "full-3d-structure-generation"],
    "framediff": ["de-novo-backbone-generation"],
    "protein-generator": ["joint-sequence-structure-generation", "functional-site-design"],
    "bindcraft": ["de-novo-non-antibody-binder-design", "target-conditioned-binder-generation"],
    "alphaproteo": ["de-novo-non-antibody-binder-design", "target-conditioned-binder-generation"],
    "boltzgen": ["target-conditioned-binder-generation", "de-novo-vhh-nanobody-design", "joint-sequence-structure-generation"],
    "rfantibody": ["de-novo-antibody-design", "de-novo-vhh-nanobody-design", "antigen-conditioned-antibody-design", "cdr-backbone-generation", "joint-cdr-sequence-structure-design"],
    "tfold": ["antigen-conditioned-antibody-design", "cdr-sequence-generation", "de-novo-antibody-design"],
    "palm-h3": ["cdr-sequence-generation", "antigen-conditioned-antibody-design"],
    "diffab": ["joint-cdr-sequence-structure-design", "antigen-conditioned-antibody-design", "cdr-sequence-generation"],
    "dymean": ["joint-cdr-sequence-structure-design", "antigen-conditioned-antibody-design"],
    "iglm": ["cdr-sequence-generation", "antibody-structure-aware-sequence-design"],
    "flowdesign": ["joint-cdr-sequence-structure-design", "cdr-sequence-generation"],
    "abdiffuser": ["joint-cdr-sequence-structure-design", "de-novo-antibody-design"],
    "humatch": ["humanization", "framework-redesign"],
    "hudiff": ["humanization", "framework-redesign", "de-novo-vhh-nanobody-design"],
    "huabdiffusion": ["humanization", "framework-redesign"],
    "esm-1v-efficient-evolution": ["single-mutation-proposal", "affinity-maturation", "ml-guided-directed-evolution"],
    "structural-evolution": ["single-mutation-proposal", "affinity-maturation", "antibody-structure-aware-sequence-design"],
    "evolvepro": ["few-shot-active-learning", "ml-guided-directed-evolution", "affinity-maturation"],
    "makowski-affinity-specificity": ["combinatorial-mutation-design", "multi-objective-optimization", "specificity-optimization", "affinity-maturation", "polyspecificity-optimization"],
}

WORKFLOW_IDS: dict[str, list[str]] = {
    "progen": ["sequence-first-de-novo"],
    "evodiff": ["sequence-first-de-novo"],
    "esm3": ["sequence-first-de-novo", "joint-multimodal-generation"],
    "proteinmpnn": ["fixed-backbone-inverse-folding"],
    "esm-if1": ["fixed-backbone-inverse-folding"],
    "ligandmpnn": ["fixed-backbone-inverse-folding"],
    "antifold": ["antibody-inverse-folding"],
    "rfdiffusion": ["de-novo-backbone-then-mpnn"],
    "rfdiffusion-aa": ["de-novo-backbone-then-mpnn"],
    "chroma": ["joint-multimodal-generation"],
    "framediff": ["de-novo-backbone-then-mpnn"],
    "protein-generator": ["joint-multimodal-generation"],
    "bindcraft": ["miniprotein-binder-bindcraft"],
    "alphaproteo": ["miniprotein-binder-bindcraft"],
    "boltzgen": ["universal-all-atom-binder"],
    "rfantibody": ["de-novo-antibody-rfantibody"],
    "tfold": ["epitope-mab-tfold"],
    "palm-h3": ["cdr-h3-sequence-palm"],
    "diffab": ["cdr-codesign-diffab"],
    "dymean": ["cdr-codesign-diffab"],
    "iglm": ["antibody-sequence-infilling"],
    "flowdesign": ["cdr-codesign-diffab"],
    "abdiffuser": ["cdr-codesign-diffab"],
    "humatch": ["humanization-framework"],
    "hudiff": ["humanization-framework"],
    "huabdiffusion": ["humanization-framework"],
    "esm-1v-efficient-evolution": ["zero-shot-mutation"],
    "structural-evolution": ["zero-shot-mutation"],
    "evolvepro": ["few-shot-active-learning"],
    "makowski-affinity-specificity": ["few-shot-active-learning"],
}

COMPATIBILITY_GROUP: dict[str, str] = {
    "progen": "sequence-only",
    "evodiff": "sequence-only",
    "esm3": "joint-sequence-structure",
    "proteinmpnn": "inverse-folding",
    "esm-if1": "inverse-folding",
    "ligandmpnn": "inverse-folding",
    "antifold": "inverse-folding",
    "rfdiffusion": "backbone-generator",
    "rfdiffusion-aa": "backbone-generator",
    "chroma": "joint-sequence-structure",
    "framediff": "backbone-generator",
    "protein-generator": "joint-sequence-structure",
    "bindcraft": "general-binder",
    "alphaproteo": "general-binder",
    "boltzgen": "general-binder",
    "rfantibody": "antibody-binder",
    "tfold": "antibody-binder",
    "palm-h3": "antibody-sequence",
    "diffab": "antibody-codesign",
    "dymean": "antibody-codesign",
    "iglm": "antibody-sequence",
    "flowdesign": "antibody-codesign",
    "abdiffuser": "antibody-codesign",
    "humatch": "humanization",
    "hudiff": "humanization",
    "huabdiffusion": "humanization",
    "esm-1v-efficient-evolution": "zero-shot-mutation",
    "structural-evolution": "zero-shot-mutation",
    "evolvepro": "few-shot-mutation",
    "makowski-affinity-specificity": "few-shot-mutation",
}

INCOMPATIBLE_GROUPS: dict[str, list[str]] = {
    "sequence-only": ["backbone-generator", "inverse-folding"],
    "inverse-folding": ["backbone-generator", "sequence-only"],
    "backbone-generator": ["sequence-only", "inverse-folding", "zero-shot-mutation"],
    "joint-sequence-structure": ["zero-shot-mutation"],
    "general-binder": ["antibody-binder", "humanization"],
    "antibody-binder": ["general-binder", "zero-shot-mutation"],
    "antibody-sequence": ["backbone-generator", "general-binder"],
    "antibody-codesign": ["inverse-folding", "zero-shot-mutation"],
    "humanization": ["general-binder", "backbone-generator"],
    "zero-shot-mutation": ["few-shot-mutation", "backbone-generator", "antibody-binder"],
    "few-shot-mutation": ["zero-shot-mutation", "backbone-generator"],
}

RELATED: dict[str, dict[str, list[str]]] = {
    "proteinmpnn": {
        "related_tools": ["esm-if1", "ligandmpnn", "antifold"],
        "alternatives": ["esm-if1", "ligandmpnn"],
        "complementary_tools": ["rfdiffusion", "rfantibody", "bindcraft"],
    },
    "antifold": {
        "related_tools": ["esm-if1", "proteinmpnn", "iglm"],
        "alternatives": ["proteinmpnn", "esm-if1"],
        "complementary_tools": ["rfantibody", "diffab"],
    },
    "rfantibody": {
        "related_tools": ["rfdiffusion", "proteinmpnn", "tfold"],
        "alternatives": ["tfold", "boltzgen"],
        "complementary_tools": ["proteinmpnn", "antifold"],
    },
    "diffab": {
        "related_tools": ["dymean", "flowdesign", "abdiffuser"],
        "alternatives": ["dymean", "flowdesign"],
        "complementary_tools": ["antifold", "iglm"],
    },
    "bindcraft": {
        "related_tools": ["alphaproteo", "boltzgen", "rfdiffusion"],
        "alternatives": ["alphaproteo", "boltzgen"],
        "complementary_tools": ["proteinmpnn"],
    },
    "iglm": {
        "related_tools": ["palm-h3", "progen", "antifold"],
        "alternatives": ["palm-h3", "progen"],
        "complementary_tools": ["antifold", "humatch"],
    },
    "humatch": {
        "related_tools": ["hudiff", "huabdiffusion"],
        "alternatives": ["hudiff", "huabdiffusion"],
        "complementary_tools": ["iglm", "antifold"],
    },
    "esm-1v-efficient-evolution": {
        "related_tools": ["structural-evolution", "evolvepro"],
        "alternatives": ["structural-evolution"],
        "complementary_tools": ["evolvepro"],
    },
}

OUTPUT_MODALITY: dict[str, list[str]] = {
    "progen": ["sequence"],
    "evodiff": ["sequence"],
    "esm3": ["sequence", "structure", "joint"],
    "proteinmpnn": ["sequence"],
    "esm-if1": ["sequence"],
    "ligandmpnn": ["sequence"],
    "antifold": ["sequence"],
    "rfdiffusion": ["structure"],
    "rfdiffusion-aa": ["structure"],
    "chroma": ["structure", "sequence", "joint"],
    "framediff": ["structure"],
    "protein-generator": ["sequence", "structure", "joint"],
    "bindcraft": ["sequence", "structure", "joint"],
    "alphaproteo": ["sequence", "structure"],
    "boltzgen": ["sequence", "structure", "joint"],
    "rfantibody": ["sequence", "structure", "joint"],
    "tfold": ["sequence", "structure"],
    "palm-h3": ["sequence"],
    "diffab": ["sequence", "structure", "joint"],
    "dymean": ["sequence", "structure", "joint"],
    "iglm": ["sequence"],
    "flowdesign": ["sequence", "structure", "joint"],
    "abdiffuser": ["sequence", "structure", "joint"],
    "humatch": ["sequence"],
    "hudiff": ["sequence"],
    "huabdiffusion": ["sequence"],
    "esm-1v-efficient-evolution": ["sequence"],
    "structural-evolution": ["sequence"],
    "evolvepro": ["sequence"],
    "makowski-affinity-specificity": ["sequence"],
}

GLOSSARY_FOR_TOOL: dict[str, list[str]] = {
    "antifold": ["inverse-folding", "cdr", "framework", "conditioning"],
    "rfantibody": ["diffusion", "inverse-folding", "epitope", "framework"],
    "diffab": ["diffusion", "equivariance", "cdr", "conditioning"],
    "proteinmpnn": ["inverse-folding", "backbone"],
    "iglm": ["protein-language-model", "infilling", "cdr"],
    "evolvepro": ["active-learning", "few-shot"],
    "humatch": ["humanization", "framework"],
}

PREDICTOR_DEPENDENCIES = [
    {
        "id": "alphafold2",
        "slug": "alphafold2",
        "name": "AlphaFold2 / ColabFold",
        "role": "Structure/self-consistency validation",
        "input_output": "Sequence → monomer/complex structure",
        "workflow_status": "External; sometimes integrated in BindCraft/RFdiffusion pipelines",
        "interpretation_boundary": "Not a generator in this catalogue",
        "source": "https://doi.org/10.1038/s41586-021-03819-2",
        "is_generator": False,
    },
    {
        "id": "alphafold3",
        "slug": "alphafold3",
        "name": "AlphaFold3",
        "role": "Complex/interaction prediction",
        "input_output": "Sequences/ligands → complex",
        "workflow_status": "External retrospective filter for RFantibody",
        "interpretation_boundary": "ipTM/pLDDT are not affinity",
        "source": "https://doi.org/10.1038/s41586-024-07487-w",
        "is_generator": False,
    },
    {
        "id": "rf2",
        "slug": "rosettafold2",
        "name": "RoseTTAFold2 / antibody-fine-tuned RF2",
        "role": "Structure/complex prediction and self-consistency",
        "input_output": "Sequence + optional target/epitope → structure",
        "workflow_status": "Integrated in RFantibody",
        "interpretation_boundary": "Predictor component only",
        "source": "https://doi.org/10.1101/2023.05.24.542179",
        "is_generator": False,
    },
    {
        "id": "tfold-predictors",
        "slug": "tfold-predictors",
        "name": "tFold-Ab / tFold-Ag",
        "role": "Antibody and antibody–antigen complex prediction",
        "input_output": "Sequences + optional epitope → structure/complex",
        "workflow_status": "Integrated in tFold System",
        "interpretation_boundary": "Predictors/rankers, not the generator itself",
        "source": "https://github.com/TencentAI4S/tfold",
        "is_generator": False,
    },
    {
        "id": "pyrosetta",
        "slug": "pyrosetta",
        "name": "PyRosetta / Rosetta",
        "role": "Relaxation, energy and interface scoring",
        "input_output": "Structure/complex → relaxed structure/scores",
        "workflow_status": "Integrated in BindCraft; common external module",
        "interpretation_boundary": "Energy/ddG is not measured affinity",
        "source": "https://www.rosettacommons.org/software/license-and-download",
        "is_generator": False,
    },
    {
        "id": "dockq",
        "slug": "dockq",
        "name": "DockQ / TM-score",
        "role": "Retrospective structural evaluation",
        "input_output": "Predicted/reference structures → metric",
        "workflow_status": "Used in dyMEAN and research benchmarks",
        "interpretation_boundary": "Evaluation only",
        "source": "https://github.com/bjornwallner/DockQ",
        "is_generator": False,
    },
    {
        "id": "md",
        "slug": "molecular-dynamics",
        "name": "Molecular dynamics",
        "role": "Conformational/interaction stress test",
        "input_output": "Selected complex → trajectories",
        "workflow_status": "Optional downstream; not routinely integrated",
        "interpretation_boundary": "MD does not generate validated binders by itself",
        "source": None,
        "is_generator": False,
    },
    {
        "id": "abnativ",
        "slug": "abnativ",
        "name": "AbNatiV / BioPhi / OASis",
        "role": "Nativeness/humanness and humanization guidance",
        "input_output": "Antibody/VHH sequence → score / guided replacements",
        "workflow_status": "Optional humanization/developability component",
        "interpretation_boundary": "Scores do not equal clinical immunogenicity",
        "source": "https://doi.org/10.1038/s42256-023-00778-3",
        "is_generator": False,
    },
    {
        "id": "camsol",
        "slug": "camsol",
        "name": "CamSol / SAP-like aggregation metrics",
        "role": "Solubility/aggregation risk",
        "input_output": "Sequence/structure → risk score",
        "workflow_status": "Optional post-generation filter",
        "interpretation_boundary": "Not a generator; assay confirmation required",
        "source": "https://doi.org/10.1038/s41326",
        "is_generator": False,
    },
    {
        "id": "experimental-assays",
        "slug": "experimental-assays",
        "name": "Experimental binding/function assays",
        "role": "Ground-truth validation",
        "input_output": "Selected sequences → binding/function/developability data",
        "workflow_status": "Mandatory for claims of improvement",
        "interpretation_boundary": "Only this layer establishes measured affinity/function",
        "source": None,
        "is_generator": False,
    },
]

# Fix CamSol DOI - Excel said 10.1038/srep01326
PREDICTOR_DEPENDENCIES[-2]["source"] = "https://doi.org/10.1038/srep01326"
